### PR TITLE
Fixes #38 parse_header() has been replaced with Header::parse()

### PR DESCRIPTION
**Pull request by jameelmoses**

### CODE REVIEW

**Comment by tdphillipsjr** [comment]
Thanks!

**Comment by jameelmoses** [comment]
Thanks for the quick merge!

**Comment by peterkeating** [comment]
@tdphillipsjr Can we get the version with this change released to packigist? I'm still seeing 2.1.2 as the latest.

**Comment by jameelmoses** [comment]
Ideally the version number would be declared in the composer.json

**Pull request merged**
